# file-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
    name: file-service
spec:
    replicas: 2
    selector:
        matchLabels:
            app: file-service
    template:
        metadata:
            labels:
                app: file-service
        spec:
            containers:
                - name: file-service
                  image: skillbridge-file-service:latest
                  ports:
                      - containerPort: 3000
                  envFrom:
                      - configMapRef:
                            name: file-env
---
apiVersion: v1
kind: Service
metadata:
    name: file-service
spec:
    type: ClusterIP
    selector:
        app: file-service
    ports:
        - port: 3000
          targetPort: 3000
