# messaging-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
    name: messaging-service
spec:
    replicas: 2
    selector:
        matchLabels:
            app: messaging-service
    template:
        metadata:
            labels:
                app: messaging-service
        spec:
            containers:
                - name: messaging-service
                  image: skillbridge-messaging-service:latest
                  ports:
                      - containerPort: 3000
                  envFrom:
                      - configMapRef:
                            name: messaging-env
---
apiVersion: v1
kind: Service
metadata:
    name: messaging-service
spec:
    type: ClusterIP
    selector:
        app: messaging-service
    ports:
        - port: 3000
          targetPort: 3000
