# payment-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
    name: payment-service
spec:
    replicas: 2
    selector:
        matchLabels:
            app: payment-service
    template:
        metadata:
            labels:
                app: payment-service
        spec:
            containers:
                - name: payment-service
                  image: skillbridge-payment-service
                  imagePullPolicy: Never
                  ports:
                      - containerPort: 3007
                  envFrom:
                      - configMapRef:
                            name: payment-env
---
apiVersion: v1
kind: Service
metadata:
    name: payment-service
spec:
    type: ClusterIP
    selector:
        app: payment-service
    ports:
        - port: 3007
          targetPort: 3007
