# search-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
    name: search-service
spec:
    replicas: 2
    selector:
        matchLabels:
            app: search-service
    template:
        metadata:
            labels:
                app: search-service
        spec:
            containers:
                - name: search-service
                  image: skillbridge-search-service:latest
                  ports:
                      - containerPort: 3000
                  envFrom:
                      - configMapRef:
                            name: search-env
---
apiVersion: v1
kind: Service
metadata:
    name: search-service
spec:
    type: ClusterIP
    selector:
        app: search-service
    ports:
        - port: 3000
          targetPort: 3000
