version: "3.9"

services:
    user-service:
        build:
            context: ./services/user-service
            dockerfile: Dockerfile
        container_name: user-service
        ports:
            - "3000:3000"
        env_file:
            - ./services/user-service/.env
        depends_on:
            - mongo

    availability-service:
        build:
            context: ./services/availability-service
            dockerfile: Dockerfile
        container_name: availability-service
        ports:
            - "3001:3001"
        env_file:
            - ./services/availability-service/.env
        depends_on:
            - mongo

    messaging-service:
        build:
            context: ./services/messaging-service
            dockerfile: Dockerfile
        container_name: messaging-service
        ports:
            - "3002:3002"
        env_file:
            - ./services/messaging-service/.env
        depends_on:
            - mongo

    search-service:
        build:
            context: ./services/search-service
            dockerfile: Dockerfile
        container_name: search-service
        ports:
            - "3003:3003"
        env_file:
            - ./services/search-service/.env
        depends_on:
            - mongo

    booking-service:
        build:
            context: ./services/booking-service
            dockerfile: Dockerfile
        container_name: booking-service
        ports:
            - "3004:3004"
        env_file:
            - ./services/booking-service/.env
        depends_on:
            - mongo

    file-service:
        build:
            context: ./services/file-service
            dockerfile: Dockerfile
        container_name: file-service
        ports:
            - "3005:3005"
        env_file:
            - ./services/file-service/.env
        depends_on:
            - mongo

    mongo:
        image: mongo:7
        container_name: mongodb
        ports:
            - "27018:27017"
        volumes:
            - mongo_data:/data/db

volumes:
    mongo_data:
