AWSTemplateFormatVersion: "2010-09-09"
Description: HTTP API Gateway mapping /users,/bookings,/availability,/mentors to edge Nginx
Parameters:
    IntegrationBaseUrl:
        Type: String
        Description: Base URL to Nginx ELB (e.g., http://a1b2c3d4e5f6-....elb.amazonaws.com)

Resources:
    HttpApi:
        Type: AWS::ApiGatewayV2::Api
        Properties:
            Name: SkillBridgeHTTP
            ProtocolType: HTTP

    # Integrations (single base, different routes via proxy)
    UsersIntegration:
        Type: AWS::ApiGatewayV2::Integration
        Properties:
            ApiId: !Ref HttpApi
            IntegrationType: HTTP_PROXY
            PayloadFormatVersion: "1.0"
            IntegrationUri: !Sub "${IntegrationBaseUrl}/users"

    BookingsIntegration:
        Type: AWS::ApiGatewayV2::Integration
        Properties:
            ApiId: !Ref HttpApi
            IntegrationType: HTTP_PROXY
            PayloadFormatVersion: "1.0"
            IntegrationUri: !Sub "${IntegrationBaseUrl}/bookings"

    AvailabilityIntegration:
        Type: AWS::ApiGatewayV2::Integration
        Properties:
            ApiId: !Ref HttpApi
            IntegrationType: HTTP_PROXY
            PayloadFormatVersion: "1.0"
            IntegrationUri: !Sub "${IntegrationBaseUrl}/availability"

    MentorsIntegration:
        Type: AWS::ApiGatewayV2::Integration
        Properties:
            ApiId: !Ref HttpApi
            IntegrationType: HTTP_PROXY
            PayloadFormatVersion: "1.0"
            IntegrationUri: !Sub "${IntegrationBaseUrl}/mentors"

    RouteUsers:
        Type: AWS::ApiGatewayV2::Route
        Properties:
            ApiId: !Ref HttpApi
            RouteKey: "ANY /users/{proxy+}"
            Target: !Sub "integrations/${UsersIntegration}"

    RouteBookings:
        Type: AWS::ApiGatewayV2::Route
        Properties:
            ApiId: !Ref HttpApi
            RouteKey: "ANY /bookings/{proxy+}"
            Target: !Sub "integrations/${BookingsIntegration}"

    RouteAvailability:
        Type: AWS::ApiGatewayV2::Route
        Properties:
            ApiId: !Ref HttpApi
            RouteKey: "ANY /availability/{proxy+}"
            Target: !Sub "integrations/${AvailabilityIntegration}"

    RouteMentors:
        Type: AWS::ApiGatewayV2::Route
        Properties:
            ApiId: !Ref HttpApi
            RouteKey: "ANY /mentors/{proxy+}"
            Target: !Sub "integrations/${MentorsIntegration}"

    Stage:
        Type: AWS::ApiGatewayV2::Stage
        Properties:
            ApiId: !Ref HttpApi
            StageName: prod
            AutoDeploy: true

Outputs:
    ApiEndpoint:
        Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/prod/"
