AWSTemplateFormatVersion: "2010-09-09"
Description: Minimal EKS (1 node) in ap-southeast-1
Parameters:
    ClusterName:
        Type: String
        Default: skillbridge-cluster
Resources:
    EKSClusterRole:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Version: "2012-10-17"
                Statement:
                    - Effect: Allow
                      Principal: { Service: eks.amazonaws.com }
                      Action: sts:AssumeRole
            ManagedPolicyArns:
                - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy

    EKSCluster:
        Type: AWS::EKS::Cluster
        Properties:
            Name: !Ref ClusterName
            Version: "1.30"
            RoleArn: !GetAtt EKSClusterRole.Arn
            ResourcesVpcConfig:
                SubnetIds: [!ImportValue SkillBridge:PublicSubnetA]

    NodeInstanceRole:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Version: "2012-10-17"
                Statement:
                    - Effect: Allow
                      Principal: { Service: ec2.amazonaws.com }
                      Action: sts:AssumeRole
            ManagedPolicyArns:
                - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
                - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
                - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly

    NodeGroup:
        Type: AWS::EKS::Nodegroup
        Properties:
            ClusterName: !Ref ClusterName
            NodeRole: !GetAtt NodeInstanceRole.Arn
            Subnets: [!ImportValue SkillBridge:PublicSubnetA]
            ScalingConfig:
                MinSize: 1
                DesiredSize: 1
                MaxSize: 2
            InstanceTypes: [t3.small]
            AmiType: AL2_x86_64

Outputs:
    ClusterName:
        Value: !Ref ClusterName
    NodeRoleArn:
        Value: !GetAtt NodeInstanceRole.Arn
