AWSTemplateFormatVersion: "2010-09-09"
Description: >
    SkillBridge unified CloudFormation stack
    (VPC + EKS Cluster + Node Group + IAM Roles + ECR Repositories)
    Region: ap-southeast-1

Parameters:
    ClusterName:
        Type: String
        Default: skillbridge-cluster
        Description: Name of the EKS Cluster

Resources:
    # =======================================================
    # Networking - VPC, Subnets (2x AZ), IGW, Route Table
    # =======================================================
    VPC:
        Type: AWS::EC2::VPC
        Properties:
            CidrBlock: 10.10.0.0/16
            EnableDnsSupport: true
            EnableDnsHostnames: true
            Tags:
                - Key: Name
                  Value: SkillBridgeVPC

    # Public subnet in AZ-0
    PublicSubnetA:
        Type: AWS::EC2::Subnet
        Properties:
            VpcId: !Ref VPC
            CidrBlock: 10.10.1.0/24
            MapPublicIpOnLaunch: true
            AvailabilityZone: !Select [0, !GetAZs ""]
            Tags:
                - Key: Name
                  Value: SkillBridgePublicSubnetA
                - Key: kubernetes.io/role/elb
                  Value: "1"
                - Key: !Sub "kubernetes.io/cluster/${ClusterName}"
                  Value: shared

    # Public subnet in AZ-1
    PublicSubnetB:
        Type: AWS::EC2::Subnet
        Properties:
            VpcId: !Ref VPC
            CidrBlock: 10.10.2.0/24
            MapPublicIpOnLaunch: true
            AvailabilityZone: !Select [1, !GetAZs ""]
            Tags:
                - Key: Name
                  Value: SkillBridgePublicSubnetB
                - Key: kubernetes.io/role/elb
                  Value: "1"
                - Key: !Sub "kubernetes.io/cluster/${ClusterName}"
                  Value: shared

    InternetGateway:
        Type: AWS::EC2::InternetGateway
        Properties:
            Tags:
                - Key: Name
                  Value: SkillBridgeIGW

    # Attach IGW to VPC (explicit dependency ordering for delete stability)
    AttachIGW:
        Type: AWS::EC2::VPCGatewayAttachment
        DependsOn:
            - PublicSubnetARouteTableAssociation
            - PublicSubnetBRouteTableAssociation
            - DefaultRoute
            - EKSNodeGroup
            - EKSCluster
        Properties:
            VpcId: !Ref VPC
            InternetGatewayId: !Ref InternetGateway

    PublicRouteTable:
        Type: AWS::EC2::RouteTable
        Properties:
            VpcId: !Ref VPC
            Tags:
                - Key: Name
                  Value: SkillBridgePublicRouteTable

    DefaultRoute:
        Type: AWS::EC2::Route
        DependsOn: AttachIGW
        Properties:
            RouteTableId: !Ref PublicRouteTable
            DestinationCidrBlock: 0.0.0.0/0
            GatewayId: !Ref InternetGateway

    PublicSubnetARouteTableAssociation:
        Type: AWS::EC2::SubnetRouteTableAssociation
        Properties:
            SubnetId: !Ref PublicSubnetA
            RouteTableId: !Ref PublicRouteTable

    PublicSubnetBRouteTableAssociation:
        Type: AWS::EC2::SubnetRouteTableAssociation
        Properties:
            SubnetId: !Ref PublicSubnetB
            RouteTableId: !Ref PublicRouteTable

    # =======================================================
    # IAM Roles
    # =======================================================
    EKSClusterRole:
        Type: AWS::IAM::Role
        Properties:
            RoleName: SkillBridgeEKSClusterRole
            AssumeRolePolicyDocument:
                Version: "2012-10-17"
                Statement:
                    - Effect: Allow
                      Principal:
                          Service: eks.amazonaws.com
                      Action: sts:AssumeRole
            ManagedPolicyArns:
                - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy

    NodeInstanceRole:
        Type: AWS::IAM::Role
        Properties:
            RoleName: SkillBridgeNodeInstanceRole
            AssumeRolePolicyDocument:
                Version: "2012-10-17"
                Statement:
                    - Effect: Allow
                      Principal:
                          Service: ec2.amazonaws.com
                      Action: sts:AssumeRole
            ManagedPolicyArns:
                - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
                - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
                - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
                - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy

    # =======================================================
    # EKS Cluster + Node Group
    # =======================================================
    EKSCluster:
        Type: AWS::EKS::Cluster
        Properties:
            Name: !Ref ClusterName
            Version: "1.30"
            RoleArn: !GetAtt EKSClusterRole.Arn
            ResourcesVpcConfig:
                SubnetIds:
                    - !Ref PublicSubnetA
                    - !Ref PublicSubnetB
                EndpointPublicAccess: true
                EndpointPrivateAccess: false

    EKSNodeGroup:
        Type: AWS::EKS::Nodegroup
        DependsOn: EKSCluster
        Properties:
            ClusterName: !Ref ClusterName
            NodeRole: !GetAtt NodeInstanceRole.Arn
            Subnets:
                - !Ref PublicSubnetA
                - !Ref PublicSubnetB
            ScalingConfig:
                MinSize: 1
                DesiredSize: 1
                MaxSize: 2
            InstanceTypes:
                - t3.small
            AmiType: AL2_x86_64
            Tags:
                Name: SkillBridgeNodeGroup

    # =======================================================
    # ECR Repositories (retained between stack cycles)
    # =======================================================
    ECRUserService:
        Type: AWS::ECR::Repository
        DeletionPolicy: Retain
        UpdateReplacePolicy: Retain
        Properties:
            RepositoryName: user-service
            ImageScanningConfiguration:
                ScanOnPush: true
            Tags:
                - Key: Name
                  Value: user-service

    ECRBookingService:
        Type: AWS::ECR::Repository
        DeletionPolicy: Retain
        UpdateReplacePolicy: Retain
        Properties:
            RepositoryName: booking-service
            ImageScanningConfiguration:
                ScanOnPush: true
            Tags:
                - Key: Name
                  Value: booking-service

    ECRAvailabilityService:
        Type: AWS::ECR::Repository
        DeletionPolicy: Retain
        UpdateReplacePolicy: Retain
        Properties:
            RepositoryName: availability-service
            ImageScanningConfiguration:
                ScanOnPush: true
            Tags:
                - Key: Name
                  Value: availability-service

    ECRSearchService:
        Type: AWS::ECR::Repository
        DeletionPolicy: Retain
        UpdateReplacePolicy: Retain
        Properties:
            RepositoryName: search-service
            ImageScanningConfiguration:
                ScanOnPush: true
            Tags:
                - Key: Name
                  Value: search-service

Outputs:
    ClusterName:
        Description: Name of the EKS Cluster
        Value: !Ref ClusterName
        Export:
            Name: SkillBridge:ClusterName

    VpcId:
        Description: ID of the VPC
        Value: !Ref VPC
        Export:
            Name: SkillBridge:VpcId

    PublicSubnetIds:
        Description: Comma-delimited list of public subnet IDs (two AZs)
        Value: !Join [",", [!Ref PublicSubnetA, !Ref PublicSubnetB]]
        Export:
            Name: SkillBridge:PublicSubnetIds
