AWSTemplateFormatVersion: "2010-09-09"
Description: Cost-optimized VPC (public-only) for EKS
Resources:
    VPC:
        Type: AWS::EC2::VPC
        Properties:
            CidrBlock: 10.10.0.0/16
            EnableDnsHostnames: true
            EnableDnsSupport: true
            Tags: [{ Key: Name, Value: SkillBridgeVPC }]

    PublicSubnetA:
        Type: AWS::EC2::Subnet
        Properties:
            VpcId: !Ref VPC
            AvailabilityZone: !Select [0, !GetAZs ""]
            CidrBlock: 10.10.1.0/24
            MapPublicIpOnLaunch: true
            Tags:
                - { Key: Name, Value: SkillBridgePublicA }

    InternetGateway:
        Type: AWS::EC2::InternetGateway

    AttachIgw:
        Type: AWS::EC2::VPCGatewayAttachment
        Properties:
            InternetGatewayId: !Ref InternetGateway
            VpcId: !Ref VPC

    PublicRouteTable:
        Type: AWS::EC2::RouteTable
        Properties:
            VpcId: !Ref VPC

    DefaultRoute:
        Type: AWS::EC2::Route
        Properties:
            RouteTableId: !Ref PublicRouteTable
            DestinationCidrBlock: 0.0.0.0/0
            GatewayId: !Ref InternetGateway

    AssocPublicA:
        Type: AWS::EC2::SubnetRouteTableAssociation
        Properties:
            SubnetId: !Ref PublicSubnetA
            RouteTableId: !Ref PublicRouteTable

Outputs:
    VpcId:
        Value: !Ref VPC
        Export:
            Name: SkillBridge:VpcId
    PublicSubnetIdA:
        Value: !Ref PublicSubnetA
        Export:
            Name: SkillBridge:PublicSubnetA
