apiVersion: v1
kind: ConfigMap
metadata:
    name: edge-nginx-conf
    namespace: skillbridge
data:
    default.conf: |
        map $http_upgrade $connection_upgrade {
          default upgrade;
          ''      close;
        }

        server {
          listen 80;

          # Common proxy headers & timeouts
          proxy_read_timeout 3600s;
          proxy_send_timeout 3600s;

          # --- Users
          location /users/ {
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_pass       http://user-service.skillbridge.svc.cluster.local:80/;
          }

          # --- Availability
          location /availability/ {
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_pass       http://availability-service.skillbridge.svc.cluster.local:80/;
          }

          # --- Search
          location /search/ {
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_pass       http://search-service.skillbridge.svc.cluster.local:80/;
          }

          # --- Bookings
          location /bookings/ {
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_pass       http://booking-service.skillbridge.svc.cluster.local:80/;
          }

          # --- Payments
          location /payments/ {
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_pass       http://payment-service.skillbridge.svc.cluster.local:80/;
          }

          # --- Files
          location /files/ {
            client_max_body_size 50m;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_pass       http://file-service.skillbridge.svc.cluster.local:80/;
          }

          # --- Pair programming (REST + WebSocket)
          location /pair/ {
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
            proxy_set_header Host $host;
            proxy_pass       http://pair-programming-service.skillbridge.svc.cluster.local:80/;
          }
          location /pair/socket.io/ {
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
            proxy_set_header Host $host;
            proxy_pass       http://pair-programming-service.skillbridge.svc.cluster.local:80/socket.io/;
          }

          # --- Messaging (REST + WebSocket)
          location /messages/ {
            proxy_set_header Host $host;
            proxy_pass       http://messaging-service.skillbridge.svc.cluster.local:80/;
          }
          location /socket.io/ {
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
            proxy_set_header Host $host;
            proxy_pass       http://messaging-service.skillbridge.svc.cluster.local:80/socket.io/;
          }
        }
