apiVersion: apps/v1
kind: Deployment
metadata:
    name: edge-nginx
    namespace: skillbridge
spec:
    replicas: 2
    selector:
        matchLabels: { app: edge-nginx }
    template:
        metadata:
            labels: { app: edge-nginx }
        spec:
            containers:
                - name: nginx
                  image: nginx:1.27-alpine
                  ports: [{ containerPort: 80 }]
                  volumeMounts:
                      - name: nginx-conf
                        mountPath: /etc/nginx/conf.d
            volumes:
                - name: nginx-conf
                  configMap:
                      name: edge-nginx-conf
                      items:
                          - key: default.conf
                            path: default.conf
---
apiVersion: v1
kind: Service
metadata:
    name: edge-nginx
    namespace: skillbridge
    annotations:
        # If you're on AWS with EKS, this makes it an internet-facing NLB
        service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
    type: LoadBalancer
    selector: { app: edge-nginx }
    ports:
        - name: http
          port: 80
          targetPort: 80
